[project]
name = "rw-rate-all"
version = "2024.1"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "ty>=0.0.55",
]

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]
